<?php

namespace Database\Seeders;

use App\Models\Moneda;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MonedaSeeder extends Seeder
{
    public function run(): void
    {
        $monedas = [
            ['codigo_clasificador' => 1, 'nombre_completo' => 'BOLIVIANO', 'estandar_iso' => 'BOB', 'simbolo' => 'Bs'],
            ['codigo_clasificador' => 46, 'nombre_completo' => 'DÓLAR ESTADOUNIDENSE', 'estandar_iso' => 'USD', 'simbolo' => '$'],
            // ['codigo_clasificador' => 125, 'nombre_completo' => 'CHELÍN SOMALÍ', 'estandar_iso' => 'SOS', 'simbolo' => 'Ssh'],
            // ['codigo_clasificador' => 126, 'nombre_completo' => 'RAND', 'estandar_iso' => 'ZAR', 'simbolo' => 'R'],
            // ['codigo_clasificador' => 127, 'nombre_completo' => 'LIBRA SURSUDANESA', 'estandar_iso' => 'SSP', 'simbolo' => '£'],
            // ['codigo_clasificador' => 128, 'nombre_completo' => 'RUPIA CEILANDESA', 'estandar_iso' => 'LKR', 'simbolo' => 'Rs'],
            // ['codigo_clasificador' => 129, 'nombre_completo' => 'LIBRA SUDANESA', 'estandar_iso' => 'SDG', 'simbolo' => '£'],
            // ['codigo_clasificador' => 130, 'nombre_completo' => 'DÓLAR SURINAMÉS', 'estandar_iso' => 'SRD', 'simbolo' => '$'],
            // ['codigo_clasificador' => 131, 'nombre_completo' => 'LILANGENI', 'estandar_iso' => 'SZL', 'simbolo' => 'L'],
            // ['codigo_clasificador' => 132, 'nombre_completo' => 'CORONA SUECA', 'estandar_iso' => 'SEK', 'simbolo' => 'kr'],
            // ['codigo_clasificador' => 133, 'nombre_completo' => 'FRANCO SUIZO', 'estandar_iso' => 'CHF', 'simbolo' => 'Fr'],
            // ['codigo_clasificador' => 134, 'nombre_completo' => 'LIBRA SIRIA', 'estandar_iso' => 'SYP', 'simbolo' => '£'],
            // ['codigo_clasificador' => 135, 'nombre_completo' => 'NUEVO DÓLAR DE TAIWÁN', 'estandar_iso' => 'TWD', 'simbolo' => 'NT$'],
            // ['codigo_clasificador' => 136, 'nombre_completo' => 'SOMONI', 'estandar_iso' => 'TJS', 'simbolo' => 'SM'],
            // ['codigo_clasificador' => 137, 'nombre_completo' => 'CHELÍN TANZANIANO', 'estandar_iso' => 'TZS', 'simbolo' => 'TSh'],
            // ['codigo_clasificador' => 138, 'nombre_completo' => 'BAT', 'estandar_iso' => 'THB', 'simbolo' => '฿'],
            // ['codigo_clasificador' => 139, 'nombre_completo' => 'PAANGA', 'estandar_iso' => 'TOP', 'simbolo' => 'T$'],
            // ['codigo_clasificador' => 140, 'nombre_completo' => 'DÓLAR TRINITENSE', 'estandar_iso' => 'TTD', 'simbolo' => 'TT$'],
            // ['codigo_clasificador' => 141, 'nombre_completo' => 'DINAR TUNECINO', 'estandar_iso' => 'TND', 'simbolo' => 'DT'],
            // ['codigo_clasificador' => 142, 'nombre_completo' => 'LIRA TURCA', 'estandar_iso' => 'TRY', 'simbolo' => '₺'],
            // ['codigo_clasificador' => 143, 'nombre_completo' => 'MANAT TURCOMANO', 'estandar_iso' => 'TMT', 'simbolo' => 'm'],
            // ['codigo_clasificador' => 144, 'nombre_completo' => 'CHELÍN UGANDÉS', 'estandar_iso' => 'UGX', 'simbolo' => 'USh'],
            // ['codigo_clasificador' => 145, 'nombre_completo' => 'GRIVNA', 'estandar_iso' => 'UAH', 'simbolo' => '₴'],
            // ['codigo_clasificador' => 146, 'nombre_completo' => 'PESO URUGUAYO', 'estandar_iso' => 'UYU', 'simbolo' => '$U'],
            // ['codigo_clasificador' => 147, 'nombre_completo' => 'SUM', 'estandar_iso' => 'UZS', 'simbolo' => 'лв'],
            // ['codigo_clasificador' => 148, 'nombre_completo' => 'VATU DO VANUATU', 'estandar_iso' => 'VUV', 'simbolo' => 'VT'],
            // ['codigo_clasificador' => 149, 'nombre_completo' => 'BOLÍVAR FUERTE', 'estandar_iso' => 'VES', 'simbolo' => 'Bs.S'],
            // ['codigo_clasificador' => 150, 'nombre_completo' => 'DONG', 'estandar_iso' => 'VND', 'simbolo' => '₫'],
            // ['codigo_clasificador' => 151, 'nombre_completo' => 'RIAL YEMENÍ', 'estandar_iso' => 'YER', 'simbolo' => '﷼'],
            // ['codigo_clasificador' => 152, 'nombre_completo' => 'KUACHA ZAMBIANO', 'estandar_iso' => 'ZMW', 'simbolo' => 'ZK'],
            // ['codigo_clasificador' => 153, 'nombre_completo' => 'DÓLAR ZIMBABUENSE', 'estandar_iso' => 'ZWL', 'simbolo' => 'Z$'],
            // ['codigo_clasificador' => 3, 'nombre_completo' => 'AFGANI', 'estandar_iso' => 'AFN', 'simbolo' => '؋'],
            // ['codigo_clasificador' => 4, 'nombre_completo' => 'LEK', 'estandar_iso' => 'ALL', 'simbolo' => 'L'],
            // ['codigo_clasificador' => 5, 'nombre_completo' => 'LIBRA ESTERLINA', 'estandar_iso' => 'GBP', 'simbolo' => '£'],
            // ['codigo_clasificador' => 6, 'nombre_completo' => 'DINAR', 'estandar_iso' => 'DZD', 'simbolo' => 'د.ج'],
            // ['codigo_clasificador' => 7, 'nombre_completo' => 'EURO', 'estandar_iso' => 'EUR', 'simbolo' => '€'],
            // ['codigo_clasificador' => 8, 'nombre_completo' => 'KUANZA DE ANGOLA', 'estandar_iso' => 'AOA', 'simbolo' => 'Kz'],
            // ['codigo_clasificador' => 9, 'nombre_completo' => 'PESO ARGENTINO', 'estandar_iso' => 'ARS', 'simbolo' => '$'],
            // ['codigo_clasificador' => 10, 'nombre_completo' => 'DRAM ARMENIO', 'estandar_iso' => 'AMD', 'simbolo' => '֏'],
            // ['codigo_clasificador' => 11, 'nombre_completo' => 'FLORÍN ARUBANO', 'estandar_iso' => 'AWG', 'simbolo' => 'ƒ'],
            // ['codigo_clasificador' => 12, 'nombre_completo' => 'DÓLAR AUSTRALIANO', 'estandar_iso' => 'AUD', 'simbolo' => '$'],
            // ['codigo_clasificador' => 13, 'nombre_completo' => 'MANAT AZERBAYANO', 'estandar_iso' => 'AZN', 'simbolo' => '₼'],
            // ['codigo_clasificador' => 14, 'nombre_completo' => 'DÓLAR DE LAS BAHAMAS', 'estandar_iso' => 'BSD', 'simbolo' => '$'],
            // ['codigo_clasificador' => 15, 'nombre_completo' => 'DINAR DE BARÉIN', 'estandar_iso' => 'BHD', 'simbolo' => '.د.ب'],
            // ['codigo_clasificador' => 16, 'nombre_completo' => 'TAKA DE BANGLADÉS', 'estandar_iso' => 'BDT', 'simbolo' => '৳'],
            // ['codigo_clasificador' => 17, 'nombre_completo' => 'DÓLAR DE LAS BARBADOS', 'estandar_iso' => 'BBD', 'simbolo' => '$'],
            // ['codigo_clasificador' => 18, 'nombre_completo' => 'RUBLO BIELORRUSO', 'estandar_iso' => 'BYN', 'simbolo' => 'Br'],
            // ['codigo_clasificador' => 19, 'nombre_completo' => 'DÓLAR BELICEÑO', 'estandar_iso' => 'BZD', 'simbolo' => '$'],
            // ['codigo_clasificador' => 20, 'nombre_completo' => 'GULTRUM BUTANÉS', 'estandar_iso' => 'BTN', 'simbolo' => 'Nu.'],
            // ['codigo_clasificador' => 21, 'nombre_completo' => 'MARCO CONVERTIBLE DE BOSNIA Y HERZEGOVINA', 'estandar_iso' => 'BAM', 'simbolo' => 'KM'],
            // ['codigo_clasificador' => 22, 'nombre_completo' => 'PULA DE BOTSUANA', 'estandar_iso' => 'BWP', 'simbolo' => 'P'],
            // ['codigo_clasificador' => 23, 'nombre_completo' => 'REAL BRASILEÑO', 'estandar_iso' => 'BRL', 'simbolo' => 'R$'],
            // ['codigo_clasificador' => 24, 'nombre_completo' => 'DÓLAR DE BRUNEI', 'estandar_iso' => 'BND', 'simbolo' => '$'],
            // ['codigo_clasificador' => 25, 'nombre_completo' => 'LEVA BÚLGARO', 'estandar_iso' => 'BGN', 'simbolo' => 'лв'],
            // ['codigo_clasificador' => 26, 'nombre_completo' => 'FRANCO CFA', 'estandar_iso' => 'XAF', 'simbolo' => 'Fr'],
            // ['codigo_clasificador' => 27, 'nombre_completo' => 'KIAT DE BIRMANIA', 'estandar_iso' => 'MMK', 'simbolo' => 'Ks'],
            // ['codigo_clasificador' => 28, 'nombre_completo' => 'FRANCO BURUNDÉS', 'estandar_iso' => 'BIF', 'simbolo' => 'Fr'],
            // ['codigo_clasificador' => 29, 'nombre_completo' => 'RIEL CAMBOYANO', 'estandar_iso' => 'KHR', 'simbolo' => '៛'],
            // ['codigo_clasificador' => 30, 'nombre_completo' => 'DÓLAR CANADIENSE', 'estandar_iso' => 'CAD', 'simbolo' => '$'],
            // ['codigo_clasificador' => 31, 'nombre_completo' => 'ESCUDO DE CABO VERDE', 'estandar_iso' => 'CVE', 'simbolo' => 'Esc'],
            // ['codigo_clasificador' => 32, 'nombre_completo' => 'DÓLAR DE LAS ISLAS CAIMÁN', 'estandar_iso' => 'KYD', 'simbolo' => '$'],
            // ['codigo_clasificador' => 33, 'nombre_completo' => 'PESO CHILENO', 'estandar_iso' => 'CLP', 'simbolo' => '$'],
            // ['codigo_clasificador' => 34, 'nombre_completo' => 'YUAN, RENMINBI', 'estandar_iso' => 'CNY', 'simbolo' => '¥'],
            // ['codigo_clasificador' => 35, 'nombre_completo' => 'PESO COLOMBIANO', 'estandar_iso' => 'COP', 'simbolo' => '$'],
            // ['codigo_clasificador' => 36, 'nombre_completo' => 'FRANCO COMORANO', 'estandar_iso' => 'KMF', 'simbolo' => 'Fr'],
            // ['codigo_clasificador' => 37, 'nombre_completo' => 'FRANCO CONGOLEÑO', 'estandar_iso' => 'CDF', 'simbolo' => 'Fr'],
            // ['codigo_clasificador' => 38, 'nombre_completo' => 'COLÓN COSTARRICENSE', 'estandar_iso' => 'CRC', 'simbolo' => '₡'],
            // ['codigo_clasificador' => 154, 'nombre_completo' => 'DÓLAR HONG KONG', 'estandar_iso' => 'HKD', 'simbolo' => 'HK$'],
            // ['codigo_clasificador' => 39, 'nombre_completo' => 'KUNA CROATA', 'estandar_iso' => 'HRK', 'simbolo' => 'kn'],
            // ['codigo_clasificador' => 40, 'nombre_completo' => 'PESO CUBANO', 'estandar_iso' => 'CUP', 'simbolo' => '$'],
            // ['codigo_clasificador' => 41, 'nombre_completo' => 'FLORÍN DE LAS ANTILLAS NEERLANDESAS', 'estandar_iso' => 'ANG', 'simbolo' => 'ƒ'],
            // ['codigo_clasificador' => 42, 'nombre_completo' => 'CORONA CHECA', 'estandar_iso' => 'CZK', 'simbolo' => 'Kč'],
            // ['codigo_clasificador' => 43, 'nombre_completo' => 'CORONA DANESA', 'estandar_iso' => 'DKK', 'simbolo' => 'kr'],
            // ['codigo_clasificador' => 44, 'nombre_completo' => 'FRANCO YIBUTIANO', 'estandar_iso' => 'DJF', 'simbolo' => 'Fr'],
            // ['codigo_clasificador' => 45, 'nombre_completo' => 'PESO DOMINICANO', 'estandar_iso' => 'DOP', 'simbolo' => 'RD$'],
            // ['codigo_clasificador' => 47, 'nombre_completo' => 'LIBRA EGIPCIA', 'estandar_iso' => 'EGP', 'simbolo' => '£'],
            // ['codigo_clasificador' => 48, 'nombre_completo' => 'COLÓN SALVADOREÑO', 'estandar_iso' => 'SVC', 'simbolo' => '₡'],
            // ['codigo_clasificador' => 49, 'nombre_completo' => 'NAKFA DE ERITREA', 'estandar_iso' => 'ERN', 'simbolo' => 'Nfk'],
            // ['codigo_clasificador' => 50, 'nombre_completo' => 'BIR', 'estandar_iso' => 'ETB', 'simbolo' => 'Br'],
            // ['codigo_clasificador' => 51, 'nombre_completo' => 'FRANCO CFP', 'estandar_iso' => 'XPF', 'simbolo' => 'Fr'],
            // ['codigo_clasificador' => 52, 'nombre_completo' => 'DALASI GAMBIANO', 'estandar_iso' => 'GMD', 'simbolo' => 'D'],
            // ['codigo_clasificador' => 53, 'nombre_completo' => 'LARI GEORGIANO', 'estandar_iso' => 'GEL', 'simbolo' => '₾'],
            // ['codigo_clasificador' => 54, 'nombre_completo' => 'CEDI DE GANA', 'estandar_iso' => 'GHS', 'simbolo' => '₵'],
            // ['codigo_clasificador' => 55, 'nombre_completo' => 'LIBRA DE GIBRALTAR', 'estandar_iso' => 'GIP', 'simbolo' => '£'],
            // ['codigo_clasificador' => 56, 'nombre_completo' => 'QUETZAL', 'estandar_iso' => 'GTQ', 'simbolo' => 'Q'],
            // ['codigo_clasificador' => 57, 'nombre_completo' => 'FRANCO GUINEANO', 'estandar_iso' => 'GNF', 'simbolo' => 'Fr'],
            // ['codigo_clasificador' => 58, 'nombre_completo' => 'GURDE', 'estandar_iso' => 'HTG', 'simbolo' => 'G'],
            // ['codigo_clasificador' => 59, 'nombre_completo' => 'LEMPIRA', 'estandar_iso' => 'HNL', 'simbolo' => 'L'],
            // ['codigo_clasificador' => 60, 'nombre_completo' => 'FORINTO', 'estandar_iso' => 'HUF', 'simbolo' => 'Ft'],
            // ['codigo_clasificador' => 61, 'nombre_completo' => 'CORONA ISLANDESA', 'estandar_iso' => 'ISK', 'simbolo' => 'kr'],
            // ['codigo_clasificador' => 62, 'nombre_completo' => 'RUPIA INDIA', 'estandar_iso' => 'INR', 'simbolo' => '₹'],
            // ['codigo_clasificador' => 2, 'nombre_completo' => 'DOLAR', 'estandar_iso' => 'USD', 'simbolo' => '$'],
            // ['codigo_clasificador' => 63, 'nombre_completo' => 'RUPIA INDONESIA', 'estandar_iso' => 'IDR', 'simbolo' => 'Rp'],
            // ['codigo_clasificador' => 64, 'nombre_completo' => 'RIAL IRANÍ', 'estandar_iso' => 'IRR', 'simbolo' => '﷼'],
            // ['codigo_clasificador' => 65, 'nombre_completo' => 'DINAR IRAKÍ', 'estandar_iso' => 'IQD', 'simbolo' => 'ع.د'],
            // ['codigo_clasificador' => 66, 'nombre_completo' => 'NUEVO SÉQUEL', 'estandar_iso' => 'ILS', 'simbolo' => '₪'],
            // ['codigo_clasificador' => 67, 'nombre_completo' => 'DÓLAR JAMAICANO', 'estandar_iso' => 'JMD', 'simbolo' => '$'],
            // ['codigo_clasificador' => 68, 'nombre_completo' => 'YEN', 'estandar_iso' => 'JPY', 'simbolo' => '¥'],
            // ['codigo_clasificador' => 69, 'nombre_completo' => 'DINAR JORDANO', 'estandar_iso' => 'JOD', 'simbolo' => 'د.ا'],
            // ['codigo_clasificador' => 70, 'nombre_completo' => 'TENGUE KAZAJO', 'estandar_iso' => 'KZT', 'simbolo' => '₸'],
            // ['codigo_clasificador' => 71, 'nombre_completo' => 'CHELÍN KENIANO', 'estandar_iso' => 'KES', 'simbolo' => 'KSh'],
            // ['codigo_clasificador' => 72, 'nombre_completo' => 'WON NORCOREANO', 'estandar_iso' => 'KPW', 'simbolo' => '₩'],
            // ['codigo_clasificador' => 73, 'nombre_completo' => 'WON SURCOREANO', 'estandar_iso' => 'KRW', 'simbolo' => '₩'],
            // ['codigo_clasificador' => 74, 'nombre_completo' => 'DINAR KUWAITÍ', 'estandar_iso' => 'KWD', 'simbolo' => 'د.ك'],
            // ['codigo_clasificador' => 75, 'nombre_completo' => 'SOM KIRGUÍS', 'estandar_iso' => 'KGS', 'simbolo' => 'с'],
            // ['codigo_clasificador' => 76, 'nombre_completo' => 'KIP', 'estandar_iso' => 'LAK', 'simbolo' => '₭'],
            // ['codigo_clasificador' => 77, 'nombre_completo' => 'LATS', 'estandar_iso' => 'LVL', 'simbolo' => 'Ls'],
            // ['codigo_clasificador' => 78, 'nombre_completo' => 'LIBRA LIBANESA', 'estandar_iso' => 'LBP', 'simbolo' => '£'],
            // ['codigo_clasificador' => 79, 'nombre_completo' => 'LOTI DE LESOTO', 'estandar_iso' => 'LSL', 'simbolo' => 'L'],
            // ['codigo_clasificador' => 80, 'nombre_completo' => 'DÓLAR LIBERIANO', 'estandar_iso' => 'LRD', 'simbolo' => '$'],
            // ['codigo_clasificador' => 81, 'nombre_completo' => 'DINAR LIBIO', 'estandar_iso' => 'LYD', 'simbolo' => 'ل.د'],
            // ['codigo_clasificador' => 82, 'nombre_completo' => 'LITAS', 'estandar_iso' => 'LTL', 'simbolo' => 'Lt'],
            // ['codigo_clasificador' => 83, 'nombre_completo' => 'PATACA DE MACAO', 'estandar_iso' => 'MOP', 'simbolo' => 'P'],
            // ['codigo_clasificador' => 84, 'nombre_completo' => 'DENAR', 'estandar_iso' => 'MKD', 'simbolo' => 'ден'],
            // ['codigo_clasificador' => 85, 'nombre_completo' => 'ARIARI', 'estandar_iso' => 'MGA', 'simbolo' => 'Ar'],
            // ['codigo_clasificador' => 86, 'nombre_completo' => 'KUACHA DE MALAUI', 'estandar_iso' => 'MWK', 'simbolo' => 'MK'],
            // ['codigo_clasificador' => 87, 'nombre_completo' => 'RINGIT', 'estandar_iso' => 'MYR', 'simbolo' => 'RM'],
            // ['codigo_clasificador' => 88, 'nombre_completo' => 'RUFIYA', 'estandar_iso' => 'MVR', 'simbolo' => '.ރ'],
            // ['codigo_clasificador' => 89, 'nombre_completo' => 'UGUIYA', 'estandar_iso' => 'MRO', 'simbolo' => 'UM'],
            // ['codigo_clasificador' => 90, 'nombre_completo' => 'RUPIA DE MAURICIO', 'estandar_iso' => 'MUR', 'simbolo' => '₨'],
            // ['codigo_clasificador' => 91, 'nombre_completo' => 'PESO MEXICANO', 'estandar_iso' => 'MXN', 'simbolo' => '$'],
            // ['codigo_clasificador' => 92, 'nombre_completo' => 'DÓLAR MICRONESIO', 'estandar_iso' => 'FMD', 'simbolo' => '$'],
            // ['codigo_clasificador' => 93, 'nombre_completo' => 'LEU MOLDAVO', 'estandar_iso' => 'MDL', 'simbolo' => 'L'],
            // ['codigo_clasificador' => 94, 'nombre_completo' => 'TUGRIK MONGOL', 'estandar_iso' => 'MNT', 'simbolo' => '₮'],
            // ['codigo_clasificador' => 95, 'nombre_completo' => 'DÍRHAM', 'estandar_iso' => 'MAD', 'simbolo' => 'د.م.'],
            // ['codigo_clasificador' => 96, 'nombre_completo' => 'METICAL', 'estandar_iso' => 'MZN', 'simbolo' => 'MT'],
            // ['codigo_clasificador' => 97, 'nombre_completo' => 'DÓLAR DE NAMIBIA', 'estandar_iso' => 'NAD', 'simbolo' => '$'],
            // ['codigo_clasificador' => 98, 'nombre_completo' => 'DÓLAR NAURUANO', 'estandar_iso' => 'AUD', 'simbolo' => '$'],
            // ['codigo_clasificador' => 99, 'nombre_completo' => 'RUPIA NEPALÍ', 'estandar_iso' => 'NPR', 'simbolo' => '₨'],
            // ['codigo_clasificador' => 100, 'nombre_completo' => 'DÓLAR DE NUEVA ZELANDA', 'estandar_iso' => 'NZD', 'simbolo' => '$'],
            // ['codigo_clasificador' => 101, 'nombre_completo' => 'CÓRDOBA NICARAGÜENSE', 'estandar_iso' => 'NIO', 'simbolo' => 'C$'],
            // ['codigo_clasificador' => 102, 'nombre_completo' => 'NAIRA NIGERIANO', 'estandar_iso' => 'NGN', 'simbolo' => '₦'],
            // ['codigo_clasificador' => 103, 'nombre_completo' => 'CORONA NORUEGA', 'estandar_iso' => 'NOK', 'simbolo' => 'kr'],
            // ['codigo_clasificador' => 104, 'nombre_completo' => 'RIAL DE OMÁN', 'estandar_iso' => 'OMR', 'simbolo' => '﷼'],
            // ['codigo_clasificador' => 105, 'nombre_completo' => 'RUPIA PAKISTANÍ', 'estandar_iso' => 'PKR', 'simbolo' => '₨'],
            // ['codigo_clasificador' => 106, 'nombre_completo' => 'BALBOA PANAMEÑO', 'estandar_iso' => 'PAB', 'simbolo' => 'B/.'],
            // ['codigo_clasificador' => 107, 'nombre_completo' => 'KINA', 'estandar_iso' => 'PGK', 'simbolo' => 'K'],
            // ['codigo_clasificador' => 108, 'nombre_completo' => 'GUARANÍ PARAGUAYO', 'estandar_iso' => 'PYG', 'simbolo' => '₲'],
            // ['codigo_clasificador' => 109, 'nombre_completo' => 'NUEVO SOL PERUANO', 'estandar_iso' => 'PEN', 'simbolo' => 'S/'],
            // ['codigo_clasificador' => 110, 'nombre_completo' => 'PESO FILIPINO', 'estandar_iso' => 'PHP', 'simbolo' => '₱'],
            // ['codigo_clasificador' => 111, 'nombre_completo' => 'ZLOTI', 'estandar_iso' => 'PLN', 'simbolo' => 'zł'],
            // ['codigo_clasificador' => 112, 'nombre_completo' => 'RIAL CATARÍ', 'estandar_iso' => 'QAR', 'simbolo' => '﷼'],
            // ['codigo_clasificador' => 113, 'nombre_completo' => 'LEU RUMANO', 'estandar_iso' => 'RON', 'simbolo' => 'lei'],
            // ['codigo_clasificador' => 114, 'nombre_completo' => 'RUBLO', 'estandar_iso' => 'RUB', 'simbolo' => '₽'],
            // ['codigo_clasificador' => 115, 'nombre_completo' => 'FRANCO RUANDÉS', 'estandar_iso' => 'RWF', 'simbolo' => 'Fr'],
            // ['codigo_clasificador' => 116, 'nombre_completo' => 'DÓLAR DEL CARIBE ORIENTAL', 'estandar_iso' => 'XCD', 'simbolo' => '$'],
            // ['codigo_clasificador' => 117, 'nombre_completo' => 'TALA', 'estandar_iso' => 'WST', 'simbolo' => 'T'],
            // ['codigo_clasificador' => 118, 'nombre_completo' => 'DOBRA', 'estandar_iso' => 'STD', 'simbolo' => 'Db'],
            // ['codigo_clasificador' => 119, 'nombre_completo' => 'RIAL SAUDÍ', 'estandar_iso' => 'SAR', 'simbolo' => '﷼'],
            // ['codigo_clasificador' => 120, 'nombre_completo' => 'DINAR SERBIO', 'estandar_iso' => 'RSD', 'simbolo' => 'дин.'],
            // ['codigo_clasificador' => 121, 'nombre_completo' => 'RUPIA SEYCHELLENSE', 'estandar_iso' => 'SCR', 'simbolo' => '₨'],
            // ['codigo_clasificador' => 122, 'nombre_completo' => 'LEONA', 'estandar_iso' => 'SLL', 'simbolo' => 'Le'],
            // ['codigo_clasificador' => 123, 'nombre_completo' => 'DÓLAR SINGAPURENSE', 'estandar_iso' => 'SGD', 'simbolo' => '$'],
            // ['codigo_clasificador' => 124, 'nombre_completo' => 'DÓLAR SALOMONENSE', 'estandar_iso' => 'SBD', 'simbolo' => '$'],
        ];

        foreach ($monedas as $moneda) {
            Moneda::updateOrCreate(
                ['codigo_clasificador' => $moneda['codigo_clasificador']], // Busca por este
                [
                    'nombre_completo' => $moneda['nombre_completo'],
                    'estandar_iso' => $moneda['estandar_iso'],
                    'simbolo' => $moneda['simbolo'],
                ]
            );
        }
    }
}